### PR TITLE
Skip pods with errored containers

### PR DESCRIPTION
**Pull request by agurgel-te**
Pods that restart on error may have their sidecars cleaned and enter a crash loop as they try and fail to reach networked resources without a sidecar.

To test, I created two of this `Job` object, one with `restartPolicy: Never` and another with `restartPolicy: OnFailure`.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: agurgel-never
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - image: alpine
        command: ["false"]
        name: main
      restartPolicy: Never
```
</details>

The expected behavior is for `onfailure-*`'s sidecar **not** to exit until the backoff limit is reached,
and for `never-*`'s sidecar to exit after each failure. The behavior seen below matches that expectation.

<details>
<summary>k get --watch po | grep 'agurgel-[on]'</summary>

It's strange that the `istio-proxy` container exiting zero makes `kubectl get` output "Completed".
`.status.phase` is correct ("Failed"). I'll report this to kubernetes/kubectl shortly.
```
agurgel-never-lxqp7                                               0/2     Pending     0               0s
agurgel-never-lxqp7                                               0/2     Pending     0               0s
agurgel-never-lxqp7                                               0/2     Init:0/1    0               0s
agurgel-onfailure-d47fg                                           0/2     Pending     0               0s
agurgel-onfailure-d47fg                                           0/2     Pending     0               0s
agurgel-onfailure-d47fg                                           0/2     Init:0/1    0               0s
agurgel-never-lxqp7                                               0/2     PodInitializing   0               5s
agurgel-onfailure-d47fg                                           0/2     PodInitializing   0               4s
agurgel-onfailure-d47fg                                           0/2     Error             0               12s
agurgel-onfailure-d47fg                                           1/2     Error             0               12s
agurgel-never-lxqp7                                               1/2     Running           0               14s
agurgel-never-lxqp7                                               2/2     Running           0               14s
agurgel-onfailure-d47fg                                           1/2     Error             1 (3s ago)      15s
agurgel-never-lxqp7                                               1/2     Error             0               16s
agurgel-never-lxqp7                                               0/2     Completed         0               17s
agurgel-onfailure-d47fg                                           1/2     CrashLoopBackOff   1 (2s ago)      16s
agurgel-never-lxqp7                                               0/2     Completed          0               19s
agurgel-never-96m9s                                               0/2     Pending            0               0s
agurgel-never-96m9s                                               0/2     Pending            0               0s
agurgel-never-96m9s                                               0/2     Init:0/1           0               0s
agurgel-never-96m9s                                               0/2     PodInitializing    0               3s
agurgel-onfailure-d47fg                                           1/2     Error              2 (15s ago)     29s
agurgel-onfailure-d47fg                                           1/2     Terminating        2 (16s ago)     30s
agurgel-never-96m9s                                               0/2     Error              0               10s
agurgel-never-96m9s                                               1/2     Error              0               10s
agurgel-onfailure-d47fg                                           1/2     Terminating        2               30s
agurgel-never-96m9s                                               0/2     Completed          0               13s
agurgel-never-96m9s                                               0/2     Completed          0               15s
agurgel-never-vx4b8                                               0/2     Pending            0               0s
agurgel-never-vx4b8                                               0/2     Pending            0               0s
agurgel-never-vx4b8                                               0/2     Init:0/1           0               0s
agurgel-never-vx4b8                                               0/2     PodInitializing    0               4s
agurgel-never-vx4b8                                               0/2     Error              0               12s
agurgel-never-vx4b8                                               1/2     Error              0               12s
agurgel-never-vx4b8                                               0/2     Completed          0               15s
agurgel-onfailure-d47fg                                           0/2     Terminating        2               62s
agurgel-onfailure-d47fg                                           0/2     Terminating        2               62s
agurgel-onfailure-d47fg                                           0/2     Terminating        2               62s
agurgel-never-vx4b8                                               0/2     Completed          0               17s
```
</details>

<details>
<summary>k get events</summary>

```
❯ kg ev --field-selector involvedObject.name=agurgel-never
LAST SEEN   TYPE      REASON                 OBJECT              MESSAGE
6m53s       Normal    SuccessfulCreate       job/agurgel-never   Created pod: agurgel-never-lxqp7
6m32s       Normal    SuccessfulCreate       job/agurgel-never   Created pod: agurgel-never-96m9s
6m6s        Normal    SuccessfulCreate       job/agurgel-never   Created pod: agurgel-never-vx4b8
5m29s       Warning   BackoffLimitExceeded   job/agurgel-never   Job has reached the specified backoff limit
❯ kg ev --field-selector involvedObject.name=agurgel-onfailure
LAST SEEN   TYPE      REASON                 OBJECT                  MESSAGE
7m10s       Normal    SuccessfulCreate       job/agurgel-onfailure   Created pod: agurgel-onfailure-d47fg
6m40s       Normal    SuccessfulDelete       job/agurgel-onfailure   Deleted pod: agurgel-onfailure-d47fg
6m40s       Warning   BackoffLimitExceeded   job/agurgel-onfailure   Job has reached the specified backoff limit
```
</details>

### CODE REVIEW

**Comment by agurgel-te** [comment]
Thoughts, @tolleiv?

**Comment by KipsasJaujoj** [comment]
Have you been using your updated version, @agurgel-te? Was it working as expected?

**Review by tolleiv — APPROVED** [review]
LGTM

**Comment by tolleiv** [comment]
Sorry I missed this one - your assumptions are correct of course

**Comment by agurgel-te** [comment]
> Was it working as expected?

Pardon the wait, @KipsasJaujoj: yes, we've been happily using this version in production.

**Pull request merged**
